[package]
name = "gb-em"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blip_buf = "0.1.4"
clap = "4.5.4"
cpal = "0.15.3"
glium = "0.34.0"
winit = "0.29.15"
